package com.mylearn.userservice.model;

import com.mylearn.common.enums.UserRole;
import jakarta.persistence.*;
import java.time.Instant;
import java.util.UUID;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

@Entity
@Table(name = "user_profiles")
@Getter
@Setter
public class UserProfile {

  /**
   * Primary key. This UUID MUST match the ID generated by the auth-service. This establishes the
   * foreign key relationship across microservice boundaries.
   */
  @Id
  @Column(name = "user_id")
  private UUID userId;

  /** The user's full, display name. */
  @Column(nullable = false)
  private String fullName;

  /** A short biography or description provided by the user/instructor. */
  @Column(columnDefinition = "TEXT")
  private String bio;

  /** URL of the user's profile picture, stored in an external service (e.g., AWS S3). */
  private String profilePictureUrl;

  /**
   * The role of the user (LEARNER, INSTRUCTOR). This is duplicated from auth-service for
   * performance reasons (avoiding repeated lookups), but should be kept synchronized if the user's
   * role changes.
   */
  @Enumerated(EnumType.STRING)
  @Column(nullable = false)
  private UserRole role;

  @CreationTimestamp
  @Column(nullable = false, updatable = false)
  private Instant createdAt;

  @UpdateTimestamp
  @Column(nullable = false)
  private Instant updatedAt;

  // Default constructor required by JPA
  public UserProfile() {}
}
