-- V1__Create_user_profiles_table.sql

-- Flyway will create the schema 'user_service' defined in application.yml if it does not exist.
-- SET search_path TO user_service;

-- Creates the table for storing non-authentication user profile data.
CREATE TABLE user_profiles (
    -- Primary key, linked to the user ID generated by auth-service.
                               user_id UUID PRIMARY KEY,

    -- The user's full, display name.
                               full_name VARCHAR(255) NOT NULL,

    -- Short biography.
                               bio TEXT,

    -- URL to the profile picture, stored externally (e.g., S3).
                               profile_picture_url VARCHAR(512),

    -- User role (LEARNER, INSTRUCTOR). Duplicated for fast lookups.
                               role VARCHAR(50) NOT NULL,

    -- Timestamps for auditing purposes.
                               created_at TIMESTAMP WITH TIME ZONE NOT NULL,
                               updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Index on full_name for potentially faster lookups/sorting in admin screens
CREATE INDEX idx_user_profiles_full_name ON user_profiles (full_name);